# Generated by Django 4.2.11 on 2025-10-13 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desk_number', models.IntegerField()),
                ('reservation', models.BooleanField()),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk_reservation.floor')),
            ],
        ),
    ]
