# Generated by Django 4.2.11 on 2025-12-22 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('desk_reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='floor',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
