# Generated by Django 4.2.11 on 2026-01-05 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desk_reservation', '0002_remove_reservation_floor_reservation_reservation_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='desk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desk_data', to='desk_reservation.desk'),
        ),
    ]
