# Generated by Django 4.2.11 on 2025-10-16 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk_reservation', '0002_alter_desk_desk_number_alter_floor_floor_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(max_length=30)),
                ('surname', models.IntegerField(max_length=30)),
                ('id_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
