# Generated by Django 4.2.11 on 2026-01-06 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desk_reservation', '0003_alter_reservation_desk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='desk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='desk_reservation.desk'),
        ),
    ]
