# Generated by Django 4.2.11 on 2025-10-19 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk_reservation', '0003_worker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worker',
        ),
        migrations.AlterField(
            model_name='desk',
            name='desk_number',
            field=models.IntegerField(default=1, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
