# Generated by Django 5.2.8 on 2026-02-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk_reservation', '0004_alter_reservation_desk'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='desk',
            constraint=models.UniqueConstraint(fields=('floor', 'desk_number'), name='unique_desk_for_floor'),
        ),
    ]
